In [3]:
import pandas as pd

In [41]:
df=pd.read_csv('caso_full.csv')
df

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,Rio Branco,1200401.0,2020-03-17,202012,413418.0,407319.0,False,False,3,0.72566,2020-03-17,0.0000,0,1,city,AC,3,0
1,NaN,12.0,2020-03-17,202012,894470.0,881935.0,False,False,3,0.33539,2020-03-17,0.0000,0,1,state,AC,3,0
2,Rio Branco,1200401.0,2020-03-18,202012,413418.0,407319.0,False,False,3,0.72566,2020-03-18,0.0000,0,2,city,AC,0,0
3,NaN,12.0,2020-03-18,202012,894470.0,881935.0,False,False,3,0.33539,2020-03-18,0.0000,0,2,state,AC,0,0
4,Rio Branco,1200401.0,2020-03-19,202012,413418.0,407319.0,False,False,4,0.96754,2020-03-19,0.0000,0,3,city,AC,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2264315,Tupirama,1721257.0,2021-06-17,202124,1922.0,1891.0,False,True,152,7908.42872,2021-06-12,0.0132,2,391,city,TO,0,0
2264316,Tupiratins,1721307.0,2021-06-17,202124,2729.0,2671.0,False,True,129,4727.00623,2021-06-12,0.0233,3,391,city,TO,0,0
2264317,Wanderlândia,1722081.0,2021-06-17,202124,11734.0,11683.0,False,True,856,7295.04005,2021-06-12,0.0175,15,416,city,TO,0,0
2264318,Xambioá,1722107.0,2021-06-17,202124,11520.0,11540.0,False,True,2182,18940.97222,2021-06-12,0.0124,27,405,city,TO,0,0
2264319,NaN,17.0,2021-06-17,202124,1590248.0,1572866.0,False,True,190543,11981.96759,2021-06-16,0.0161,3061,457,state,TO,0,0

In [8]:
df['state'].value_counts()

MG    332837
SP    265822
RS    194502
BA    169181
PR    159004
SC    120594
GO     96845
PB     90396
MA     89894
PI     88788
CE     79096
PE     78640
RN     69166
PA     61450
MT     56525
TO     56150
AL     42688
RJ     40850
ES     34314
MS     31737
SE     31415
AM     26791
RO     22106
AC      9641
RR      7253
AP      7250
DF      1385
Name: state, dtype: int64

In [9]:
sp=df.loc[df['state']=='SP']
sp

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
1942348,São Paulo,3550308.0,2020-02-25,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-25,0.0000,0,1,city,SP,1,0
1942349,NaN,35.0,2020-02-25,202009,46289333.0,45919049.0,False,False,1,0.00216,2020-02-25,0.0000,0,1,state,SP,1,0
1942350,São Paulo,3550308.0,2020-02-26,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-26,0.0000,0,2,city,SP,0,0
1942351,NaN,35.0,2020-02-26,202009,46289333.0,45919049.0,False,False,1,0.00216,2020-02-26,0.0000,0,2,state,SP,0,0
1942352,São Paulo,3550308.0,2020-02-27,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-27,0.0000,0,3,city,SP,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2208165,Álvares Florence,3501202.0,2021-06-17,202124,3647.0,3679.0,False,True,443,12146.97011,2021-06-16,0.0293,13,385,city,SP,0,0
2208166,Álvares Machado,3501301.0,2021-06-17,202124,24998.0,24915.0,False,True,1798,7192.57541,2021-06-16,0.0289,52,416,city,SP,0,0
2208167,Álvaro de Carvalho,3501400.0,2021-06-17,202124,5274.0,5227.0,False,True,148,2806.21919,2021-06-16,0.0608,9,406,city,SP,0,0
2208168,Óleo,3533809.0,2021-06-17,202124,2471.0,2496.0,False,True,89,3601.78066,2021-06-16,0.0112,1,364,city,SP,0,0
2208169,NaN,35.0,2021-06-17,202124,46289333.0,45919049.0,True,False,3525021,7615.19074,2021-06-17,0.0342,120524,479,state,SP,15054,619

In [31]:
 sp_estado=sp.loc[sp['city'].isnull()]# o que fazer com essas linhas?

In [32]:
sp_estado['new_deaths'].sum() #esse é o valor certo do estado

120524

In [39]:
sp['new_deaths'].sum() #nesse valor tem que tirar os nulos, que são o do estado.

119904

In [37]:
sp=sp.dropna()

In [38]:
sp

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
1942348,São Paulo,3550308.0,2020-02-25,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-25,0.0000,0,1,city,SP,1,0
1942350,São Paulo,3550308.0,2020-02-26,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-26,0.0000,0,2,city,SP,0,0
1942352,São Paulo,3550308.0,2020-02-27,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-27,0.0000,0,3,city,SP,0,0
1942354,São Paulo,3550308.0,2020-02-28,202009,12325232.0,12252023.0,False,False,2,0.01623,2020-02-28,0.0000,0,4,city,SP,1,0
1942356,São Paulo,3550308.0,2020-02-29,202009,12325232.0,12252023.0,False,False,2,0.01623,2020-02-29,0.0000,0,5,city,SP,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2208164,Águas de São Pedro,3500600.0,2021-06-17,202124,3521.0,3451.0,False,True,288,8179.49446,2021-06-16,0.0243,7,434,city,SP,0,0
2208165,Álvares Florence,3501202.0,2021-06-17,202124,3647.0,3679.0,False,True,443,12146.97011,2021-06-16,0.0293,13,385,city,SP,0,0
2208166,Álvares Machado,3501301.0,2021-06-17,202124,24998.0,24915.0,False,True,1798,7192.57541,2021-06-16,0.0289,52,416,city,SP,0,0
2208167,Álvaro de Carvalho,3501400.0,2021-06-17,202124,5274.0,5227.0,False,True,148,2806.21919,2021-06-16,0.0608,9,406,city,SP,0,0
2208168,Óleo,3533809.0,2021-06-17,202124,2471.0,2496.0,False,True,89,3601.78066,2021-06-16,0.0112,1,364,city,SP,0,0

In [44]:
sp.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
1942348,São Paulo,3550308.0,2020-02-25,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-25,0.0,0,1,city,SP,1,0
1942350,São Paulo,3550308.0,2020-02-26,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-26,0.0,0,2,city,SP,0,0
1942352,São Paulo,3550308.0,2020-02-27,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-27,0.0,0,3,city,SP,0,0
1942354,São Paulo,3550308.0,2020-02-28,202009,12325232.0,12252023.0,False,False,2,0.01623,2020-02-28,0.0,0,4,city,SP,1,0
1942356,São Paulo,3550308.0,2020-02-29,202009,12325232.0,12252023.0,False,False,2,0.01623,2020-02-29,0.0,0,5,city,SP,0,0

In [47]:
sp.columns

Index(['city', 'city_ibge_code', 'date', 'epidemiological_week',
       'estimated_population', 'estimated_population_2019', 'is_last',
       'is_repeated', 'last_available_confirmed',
       'last_available_confirmed_per_100k_inhabitants', 'last_available_date',
       'last_available_death_rate', 'last_available_deaths', 'order_for_place',
       'place_type', 'state', 'new_confirmed', 'new_deaths'],
      dtype='object')

,Cidades,Mortes
0,1942348 São Paulo 1942350 ...,1942348 0 1942350 0 1942352 0 1942354...

In [85]:
sp.groupby(by='epidemiological_week').sum().sort_values('new_deaths')

,city_ibge_code,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_death_rate,last_available_deaths,order_for_place,new_confirmed,new_deaths
epidemiological_week,,,,,,,,,,,,
202009,1.775154e+07,61626160.0,61260115.0,0,0,7,5.679000e-02,0.0000,0,15,2,0
202010,2.839946e+07,86418925.0,85903608.0,0,1,34,9.704900e-01,0.0000,0,64,11,0
202011,6.374101e+07,88265414.0,87724045.0,0,3,238,8.535680e+00,0.0000,0,154,52,0
202012,3.463465e+08,129840263.0,128965913.0,0,29,1578,6.251594e+01,0.0985,27,522,272,9
202013,7.244997e+08,164615098.0,163397844.0,0,101,5204,2.722875e+02,7.4455,265,1620,843,57
...,...,...,...,...,...,...,...,...,...,...,...,...
202118,1.593207e+10,324025331.0,321433343.0,0,0,20694561,2.916744e+07,132.0503,691005,1660064,93484,4458
202117,1.593207e+10,324025331.0,321433343.0,0,645,20093546,2.812196e+07,129.3878,661903,1628459,92077,4518
202113,1.593207e+10,324025331.0,321433343.0,0,0,17288826,2.367063e+07,115.5318,521454,1502039,109688,5003
202114,1.593207e+10,324025331.0,321433343.0,0,0,18038425,2.480863e+07,119.1392,557081,1533644,115150,5657
202115,1.593207e+10,324025331.0,321433343.0,0,0,18808362,2.607245e+07,123.2966,597828,1565249,104399,5690